feat!: update npm dependencies to latest versions
MobieTrain/eslint-config pull request #20
Opened 2024-05-21 14:33 UTC by cyck

2024-05-22 12:44 UTC, celsopalmeiraneto requested changes

2024-05-22 12:44 UTC, celsopalmeiraneto commented on .prettierrc.cjs
Should we add `prettier` as one of the `devDependencies` of this project?

2024-05-22 13:25 UTC, cyck commented on .prettierrc.cjs
Honestly, I don't want to deal with that within this scope. I'm happy to remove the config, tho

2024-05-23 08:58 UTC, celsopalmeiraneto commented on .prettierrc.cjs
Fine by me.

2024-05-23 09:20 UTC, cyck commented on .prettierrc.cjs
Done 🙇🏼

2024-05-23 12:53 UTC, celsopalmeiraneto approved these changes

2024-05-23 13:06 UTC, sikozonpc approved these changes

2024-05-23 13:28 UTC, merged